Repository kzi-nastava/iks-project-event-planner-siit-2024-team-2, pull requests merged in 2025-08, with the labels that each got.

#27 bugfix Load only my events
  src/app/layout/my-events/my-events.component.ts
  src/app/services/event.service.ts
Labels: bugfix

#28 6.3 Quick Registration
  src/app/app.component.ts
  src/app/app.routes.ts
  src/app/interceptors/jwt.interceptor.ts
  src/app/layout/accept-invitation-component/accept-invitation-component.ts
  src/app/layout/auth/login/login.component.ts
  src/app/layout/auth/register/register.component.html
  src/app/layout/auth/register/register.component.ts
  src/app/layout/home/home.component.css
  src/app/layout/home/home.component.html
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/nav-bar/nav-bar.component.ts
  src/app/layout/new-service/new-service.component.ts
  src/app/layout/profile/profile.component.html
  src/app/layout/profile/profile.component.ts
  src/app/model/event/invitation.ts
  src/app/services/auth-service.service.ts
  src/app/services/communication/notification.service.ts
  src/app/services/communication/socket.service.ts
  src/app/services/dtos/auth/login-response.ts
  src/app/services/dtos/auth/quick-login.dto.ts
  src/app/services/dtos/communication/notification.dto.ts
  src/app/services/dtos/event/invitation-error-type.ts
  src/app/services/dtos/event/invitation-error.dto.ts
  src/app/services/dtos/user/user-role.ts
  src/app/services/dtos/user/user.ts
  src/app/services/utils/toast-service.ts
Labels: feat

#31 8.3 profile page
  default-profile.jpg
  src/app/dialog/delete-dialog/delete-dialog.component.ts
  src/app/layout/auth/register/register.component.css
  src/app/layout/auth/register/register.component.html
  src/app/layout/auth/register/register.component.ts
  src/app/layout/my-products/my-products.component.html
  src/app/layout/my-products/my-products.component.ts
  src/app/layout/new-product/new-product.component.ts
  src/app/layout/profile/profile.component.html
  src/app/layout/profile/profile.component.ts
  src/app/services/auth-service.service.ts
  src/app/services/dtos/user/user.ts
  src/app/services/product.service.ts
  src/app/services/profile.service.ts
Labels: feat

#35 5.7 Report on Service Product Details Page
  src/app/dialog/activity-form-dialog/activity-form-dialog.component.ts
  src/app/dialog/delete-dialog/delete-dialog.component.ts
  src/app/layout/agenda/agenda.component.ts
  src/app/layout/category-notification/category-notification.component.html
  src/app/layout/category-notification/category-notification.component.ts
  src/app/layout/event-details/event-details.component.html
  src/app/layout/my-products/my-products.component.ts
  src/app/layout/new-event-type/new-event-type.component.ts
  src/app/layout/new-product/new-product.component.html
  src/app/layout/new-product/new-product.component.ts
  src/app/layout/new-service/new-service.component.html
  src/app/layout/new-service/new-service.component.ts
  src/app/layout/sp-details/sp-details-component.css
  src/app/layout/sp-details/sp-details-component.html
  src/app/layout/sp-details/sp-details-component.ts
  src/app/model/communication/notification.ts
  src/app/model/event/event.ts
  src/app/model/service-product/product.ts
  src/app/model/service-product/service-product.ts
  src/app/model/service-product/service.ts
  src/app/model/user/service-product-provider.ts
  src/app/model/user/user-report.ts
  src/app/model/user/user.ts
  src/app/services/dtos/service-product/product-details.dto.ts
  src/app/services/dtos/service-product/product.dto.ts
  src/app/services/dtos/user/company-info.dto.ts
  src/app/services/dtos/user/user-info.dto.ts
  src/app/services/dtos/user/user.dto.ts
  src/app/services/event.service.ts
  src/app/services/product.service.ts
  src/app/services/profile.service.ts
  src/app/shared/map/map.component.ts
  src/app/shared/map/map.service.ts
Labels: improvement, refactor

#29 4.2 Budget Management
  src/app/app.routes.ts
  src/app/dialog/delete-dialog/delete-dialog.component.ts
  src/app/layout/budget/budget.component.css
  src/app/layout/budget/budget.component.html
  src/app/layout/budget/budget.component.spec.ts
  src/app/layout/budget/budget.component.ts
  src/app/layout/my-events/my-events.component.html
  src/app/layout/my-events/my-events.component.ts
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/new-event/new-event.component.ts
  src/app/model/budget/booking.ts
  src/app/model/budget/budget.ts
  src/app/model/budget/purchase.ts
  src/app/model/event/event.ts
  src/app/services/budget.service.spec.ts
  src/app/services/budget.service.ts
  src/app/services/dtos/event/create-budget.dto.ts
  src/app/services/event.service.ts
  src/app/services/service-product/service-product.service.ts
Labels: feat

#33 8.3 Using Profile Pictures
  default-profile.jpg
  public/images/avatar.png
  public/images/avatar.svg
  src/app/app.routes.ts
  src/app/layout/home/home.component.html
  src/app/layout/home/home.component.ts
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/profile/profile.component.html
  src/app/layout/profile/profile.component.ts
  src/app/services/dtos/event/event-summary.dto.ts
  src/app/services/dtos/service-product/service-product-summary.dto.ts
  src/app/utils/image-fallback.ts
Labels: improvement

#36 5.5 Admin Review System
  src/app/app.routes.ts
  src/app/layout/admin-reviews/admin-reviews.component.css
  src/app/layout/admin-reviews/admin-reviews.component.html
  src/app/layout/admin-reviews/admin-reviews.component.spec.ts
  src/app/layout/admin-reviews/admin-reviews.component.ts
  src/app/layout/nav-bar/nav-bar.component.html
  src/app/layout/notifications/notifications.component.html
  src/app/layout/notifications/notifications.component.ts
  src/app/model/communication/notification.ts
  src/app/model/review/event-review.ts
  src/app/model/review/review.ts
  src/app/model/review/service-product-review.ts
  src/app/model/service-product/service-product.ts
  src/app/model/utils/review-status.ts
  src/app/services/dtos/review/review-comment.dto.ts
  src/app/services/dtos/review/review-status.dto.ts
  src/app/services/dtos/review/review-type.ts
  src/app/services/dtos/review/review.dto.ts
  src/app/services/service-product/review.service.spec.ts
  src/app/services/service-product/review.service.ts
  src/app/services/service-product/service-product.service.ts
  src/app/utils/format-util.service.spec.ts
  src/app/utils/format-util.service.ts
Labels: feat
